### ISSUE TITLE
Figure in 7.2 Resources

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/gp-data-service-linking-simplification#44] opened 2022-01-31 20:25 UTC
I have a few questions / comments regarding the figure in 7.2 Resources:

![annotated image](https://user-images.githubusercontent.com/11427611/151866119-393827c7-7388-4bee-84e5-e3637b3a2486.png)

I tried to create an adapted version – for discussion – and of course the contents of a new figure would depend on the answers to some of my questions.

![simplified](https://user-images.githubusercontent.com/11427611/151867333-898435c2-dfc2-4591-8ac7-03c42d8b793a.jpg)

([as powerpoint](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/files/7973993/INSPIRE.models_v1.1.pptx))

**Comment by MarieLambois** [comment] 2022-06-21 08:34
I am not really convinced that scenario 1 and 2 have still a meaning in the simplified approach. From what I understood, I also tried to improve @heidivanparys diagram a little bit. I re-introduce the (now optional) link to the Dataset MD from the service MD) and precised the the INSPIRE extension in the GetCapabilities is now optional. 
![image](https://user-images.githubusercontent.com/12797943/174754795-5a2e38d8-82df-4ce8-ba8c-a9de217d9a4c.png)
To make really appear that it is a  simplification I also drafted another diagram with only the mandatory elments:
![image](https://user-images.githubusercontent.com/12797943/174754951-122e80cd-7a8f-4811-8ffb-1c0be05a1c82.png)
[INSPIRE.models_v1.2.pptx](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/files/8947166/INSPIRE.models_v1.2.pptx)

**Comment by heidivanparys** [comment] 2022-06-21 13:24
Meeting 2022-06-21:

- general agreement to use two figures
- add note regarding the Spatial Data Set Identifier (see also #52)
- change the colours so there is a difference between mandatory and optional (dark blue vs light blue)

**Comment by jescriu** [comment] 2022-07-01 17:07
Dear @heidivanparys,

Regarding
> I have a few questions / comments regarding the figure in 7.2 Resources:
and your 1st question/comment:
> Is this figure supposed to illustrate scenario 2 only? Or is it supposed to give a general overview overview of this specification?

I think that the initial graphic was intended to provide a general overview of the scenarios (1 and 2) and possibilities, once introduced the new data-service linking simplification approach. But @dartasensi may confirm much better than me.

The rest of your comments and proposals makes totally sense to me.

Also the new "simplified" versions of the graphics provided by @MarieLambois - Just to comment two thing on them:

- In the first simplified graphic, please correct the double 's' typo in '[O] Coupled Re**ss**ources'.
- Note that the second simplified graphic is only representing the data-service linking simplification approach.

I will provide input on #52 as soon as possible, so there might be some implication to the final note on 'Spatial Data Set Identifier' to be added here. 

Who will be finishing the editorial changes to the graphics above?

Jordi

**Comment by idevisser** [comment] 2022-07-04 14:59
I will do the editoral changes, as part of the presentation in the MIG-T

**Comment by idevisser** [comment] 2022-07-05 09:14
Updated version;

![image](https://user-images.githubusercontent.com/10847083/177293858-aef1cd2f-e572-4ca9-a952-2dbcc36cb998.png)

![image](https://user-images.githubusercontent.com/10847083/177293958-cd5933c6-8b72-43e8-bc85-dc48733997d6.png)

INSPIRE.models_v1.3

**Comment by jescriu** [comment] 2022-07-05 09:30
Dear Ine,
As I warned in my last post, the note regarding the Spatial Data Set Identifier for services will require some amendment.
I will provide input on #52 today.

**Comment by jescriu** [comment] 2022-09-23 08:15
The new Graphics ([INSPIRE.models_v1.3.pptx](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/files/9045085/INSPIRE.models_v1.3.pptx)) are ready to be added in https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/blob/main/proposals/JRC/ds-linking-simplification-good-practice.md#72-resources-

Candidate note on 'Spatial Data Set Identifier' ready in issue #52:
https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/issues/52#issuecomment-1176350451

**Comment by heidivanparys** [comment] 2022-10-04 19:31
The legend should be updated to describe scenario 3 as well.

**Comment by idevisser** [comment] 2022-10-05 12:16
I have update the legend as following;
Note:
•	Regarding the INSPIRE compliant Service MD; In an INSPIRE Network Service – Scenario 1 implementation, this Service MD will not contain all INSPIRE metadata elements but contain a link to the Service MD in the Discovery Service. Scenario 2 and 3 have no separate Service MD in the Discovery Service, Scenario 2 makes use of extended capabilities, scenario 3 remaps the metadata elements to existing capability elements and the dataset metadata.
•	Regarding the Spatial Data Set Identifier; The IR on metadata is not including the Unique resource identifier as a required metadata element to be applied to services. The TG for Download and View services specify a WxS/Atom metadata element that contains the Unique Resource Identifier of the Spatial Data Set. In the current INSPIRE Geoportal this is used, in some cases, to establish a link between data and service for quality control purposes. The Coupled resource would be enough for data-service linking purposes, as is used e.g. in case of a WMS in the current INSPIRE Geoportal.

**Comment by idevisser** [comment] 2022-10-05 12:18
[INSPIRE.models_v1.4.pptx](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/files/9715501/INSPIRE.models_v1.4.pptx)

**Comment by jescriu** [comment] 2022-11-07 00:53
Dear @idevisser, @heidivanparys, @MarieLambois, @AntoRot,
I prepared a new final version of the file with the graphics with minor aesthetic changes.
[INSPIRE_models_v1.5.pptx](https://github.com/INSPIRE-MIF/gp-data-service-linking-simplification/files/9947292/INSPIRE_models_v1.5.pptx)
I will include this version in Section 7.2 of Part A consolidated proposal, and subsequently proceed to close this issue.

**Closed by jescriu** 2022-11-07 00:53 UTC
